### PR TITLE
Added CONTRIBUTING.md file with guidelines for external contributors

### PR DESCRIPTION
**Pull request by bryk**

### CODE REVIEW

**Comment by gmarek** [comment]
LGTM

@eparis @smarterclayton @bgrant0607 @thockin - can one of you please merge this PR? Also is it possible to have owner in Europe other than @fgrzadkowski, as currently he's the single point of failure (well - latency).

**Comment by bryk** [comment]
Actually, I can do the merge. Will be doing this till we have local team members that can merge PRs.

**Comment by thockin** [comment]
Why does the repo have the word "kubernetes" in it?  Isn't it sort of
redundant with the org name?  Could it be shortened to kube-?

**Comment by bgrant0607** [comment]
@thockin Ask @aronchick

**Comment by aronchick** [comment]
Fair enough. We should either go kubernetes in everything, or nothing. Given Docker's naming (https://github.com/docker), I suppose the latter is better.

**Comment by bryk** [comment]
Both "kubernetes/console" and "kubernetes/kubernetes-console" are fine. I can change the name if this gets enough support.

**Comment by bgrant0607** [comment]
Just "console" sgtm.

**Comment by bryk** [comment]
Name changed to "console".

**Pull request merged**
